### ISSUE TITLE
Error with permissions on v2.4.9.2 Docker install

### ISSUE THREAD

**Issue by SiskoUrso** [pablouser1/ProxiTok#158]
Before submitting an issue, please make sure you are using the latest version of ProxiTok.

**Describe the bug**
After updating to v2.4.9.2 I receive the following error in the logs and prevents it from loading: 

proxitok-web     | Cannot create /var/run/apache2/socks with owner www-data.
proxitok-web     | Please fix manually. Aborting.

Was working previous to updating, I updated by running "docker compose pull" and "git pull" for the most recent repo. When the issue continued I wiped out the ProxiTok dir and deleted the proxitok_proxitok-cache volume and closed the repo again and followed install/run directions for Docker and the issue continued. 

**To Reproduce**
1. git clone https://github.com/pablouser1/ProxiTok
2. docker compose pull to grab new images
3. APP_URL='https://myinstancenamehere' docker compose up
4. instance is not reachable
5. docker compose logs -f
6. find error as listed above

**Expected behavior**
Expected intance to launch without errors and reachable 

**Logs**
proxitok-redis   | 1:C 08 Jul 2023 21:51:27.383 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
proxitok-web     | rmdir: failed to remove '/var/run/apache2/socks.mUX75KybRi': Operation not permitted
proxitok-redis   | 1:C 08 Jul 2023 21:51:27.383 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
proxitok-signer  | App listening on port: 8080
proxitok-redis   | 1:C 08 Jul 2023 21:51:27.383 # Configuration loaded
proxitok-web     | Cannot create /var/run/apache2/socks with owner www-data.
proxitok-web     | Please fix manually. Aborting.
proxitok-redis   | 1:M 08 Jul 2023 21:51:27.386 # Server initialized

**Enviroment (please complete the following information):**
Docker

- Deployment method (if possible): docker

**Comment by xbdmHQ** [comment]
> 

Try this:

```
docker-compose down
sudo rm -r (folder name)
re-git clone the repo https://github.com/pablouser1/ProxiTok.git tiktok
cd tiktok
nano docker-compose.yml
docker-compose pull
docker-compose up -d
```

**Comment by SiskoUrso** [comment]
> > 
> 
> Try this:
> 
> ```
> docker-compose down
> sudo rm -r (folder name)
> re-git clone the repo https://github.com/pablouser1/ProxiTok.git tiktok
> cd tiktok
> nano docker-compose.yml
> docker-compose pull
> docker-compose up -d
> ```

Hey there thanks for the reply. I tried those steps but still having the same error.

**Comment by koalaeagle** [comment]
Just reporting that I have the same issue. As a workaround, I am using a version from 27 days ago (I think we only have latest tag, so not sure what version it was) which is working fine.

My update to docker compose for this workaround (changed for web container):

```
#image: ghcr.io/pablouser1/proxitok:master
image: ghcr.io/pablouser1/proxitok@sha256:80ccad758027ff0367ee640935ec97fcb32f42fdab5a800032ec0a63690f1196
```

Image list for reference: https://github.com/pablouser1/ProxiTok/pkgs/container/proxitok/versions?filters%5Bversion_type%5D=untagged

**Comment by SiskoUrso** [comment]
@koalaeagle Thanks for the workaround, I used the image in your snippet there and able to get my instance back up and running again on an older version for now.

**Comment by EsmailELBoBDev2** [comment]
Thank you @koalaeagle, I can confirm this workaround works with me too

**Comment by Umpaaa** [comment]
Also worked for me, thank you

**Comment by Znuff** [comment]
This is happening due to the following lines in the `docker-compose.yaml` file:

```
    cap_drop:
      - ALL
```

Image will start just fine if you remove this. Not sure why the author decided to drop all permissions in there, seems like a weird thing to do.

**Comment by EsmailELBoBDev2** [comment]
> This is happening due to the following lines in the `docker-compose.yaml` file:
> 
> ```
>     cap_drop:
>       - ALL
> ```
> 
> Image will start just fine if you remove this. Not sure why the author decided to drop all permissions in there, seems like a weird thing to do.

Looking more into it, it seems the dev trying to limit the permissions which is good for security but for whatever reason it breaks

**Comment by Znuff** [comment]
Line 44 has nothing to do with it. That's a different image.

The php8.2-apache image does this: https://github.com/docker-library/php/blob/c4b2441940483e6063a1456277b6256ef377e354/8.2/bullseye/apache/Dockerfile#L74

So permissions/capabilities to rmdir that directory are required. Not entirely sure which capability would offer that, but at that point it doesn't really matter, IMO.

**Comment by pablouser1** [comment]
Hi. Indeed it looks like something changed with php8.2-apache, but right now I'm looking to change the webserver to nginx (and reducing the image size in the process) so it isn't that important.

All security changes made to `docker-compose.yml` were done (and explained) in this pull request: #135

**Comment by pablouser1** [comment]
Should have been fixed with 4f906ef80162bb2f7714e14d4ad5db0c22b5f12d. Now I can run `docker compose up` and have everything working out of the box.

The image now uses [TrafeX/docker-php-nginx](https://github.com/TrafeX/docker-php-nginx) as the base image for building as it has nginx pre-configured.

**Comment by xbdmHQ** [comment]
WTF is going on with Prokitok, this is the only service which has issues lol

**Comment by xbdmHQ** [comment]
Issue didn't work lmao

**Comment by xbdmHQ** [comment]
The rest works, but ```proxitok-web``` logs:

```
2023-07-27 20:37:30,207 INFO supervisord started with pid 1
2023-07-27 20:37:31,213 INFO spawned: 'nginx' with pid 7
2023-07-27 20:37:31,217 INFO spawned: 'php-fpm' with pid 8
[27-Jul-2023 20:37:31] NOTICE: fpm is running, pid 8
[27-Jul-2023 20:37:31] NOTICE: ready to handle connections
2023-07-27 20:37:32,245 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-07-27 20:37:32,245 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by xbdmHQ** [comment]
@pablouser1

**Comment by xbdmHQ** [comment]
Ok, finally got it up and running still took a bit of effort tbh...

**Comment by Znuff** [comment]
Way to sound like a dick dude. This is not your blogging platform, try to keep it short and if you have actual issues make a new issue. This was not related to whatever you experienced there.

Some common sense would help you a long way.

**Comment by EsmailELBoBDev2** [comment]
uhh @pablouser1 I still get 502 Bad Gateway. I made sure to `git pull` and removed `proxitok-cache` folder but still no luck

**Comment by AlyoshaVasilieva** [comment]
I had to do `docker volume rm proxitok_proxitok-cache` with the container down, afterwards it seems to be working

**Comment by EsmailELBoBDev2** [comment]
still face same problem, can someone share their docker compose with me?

**Comment by Znuff** [comment]
Just do the following.

### 1. stop the containers

Just navigate to the project's directory, and issue:

```
docker compose stop

docker compose rm -f
```
*note: if you don't have the `docker-compose-plugin` installed, substitute with the command `docker-compose`*
Don't worry about deleting the containers, they'll get recreated.

### 2. remove the old image
Get the ID of the image(s):
```
# docker image list -a
REPOSITORY                    TAG        IMAGE ID       CREATED        SIZE
ghcr.io/pablouser1/proxitok   master     a1c5b22cdc69   8 days ago     120MB
redis                         7-alpine   a9dda5a2aee4   3 weeks ago    30.6MB
ghcr.io/pablouser1/signtok    master     f80cd8422028   8 months ago   553MB
```
Grab the ID of the `proxitok` image, in my case `a1c5b22cdc69`, yours will probably be different!
```
docker image rm a1c5b22cdc69
```
*note: if you get an error that the image is in use, then you didn't run the command I mentioned above*
### 3. start the containers
Make sure you're in the `proxitok` directory, then:
```
docker compose up
```
This will fetch the proper images and start the containers.

------
## Alternative
To always fetch and build the image locally, for example if you want to change some layout things or whatever, you could always alter the `docker-compose.yml` file to instead build the image locally.

You can do this by replacing the `image` key:
```
    image: ghcr.io/pablouser1/proxitok:master
```
With the following:
```
    build:
      context: ./
      dockerfile: ./Dockerfile
```

**Comment by EsmailELBoBDev2** [comment]
Thank you for your detailed explanation but still I get 502 when I use `ghcr.io/pablouser1/proxitok:master` so I'm going to post logs and my docker compose:

logs:
```
 ✔ Container proxitok-redis   Created                                                                                                                 9.1s 
 ✔ Container proxitok-signer  Created                                                                                                                 9.2s 
 ✔ Container proxitok-web     Created                                                                                                                 2.2s 
Attaching to proxitok-redis, proxitok-signer, proxitok-web
proxitok-redis   | 1:C 04 Aug 2023 01:17:15.548 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
proxitok-redis   | 1:C 04 Aug 2023 01:17:15.548 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
proxitok-redis   | 1:C 04 Aug 2023 01:17:15.548 # Configuration loaded
proxitok-redis   | 1:M 04 Aug 2023 01:17:15.549 # Server initialized
proxitok-redis   | 1:M 04 Aug 2023 01:17:15.549 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
proxitok-web     | 2023-08-04 01:17:17,165 INFO supervisord started with pid 1
proxitok-web     | 2023-08-04 01:17:18,167 INFO spawned: 'nginx' with pid 7
proxitok-web     | 2023-08-04 01:17:18,169 INFO spawned: 'php-fpm' with pid 8
proxitok-web     | [04-Aug-2023 01:17:18] NOTICE: fpm is running, pid 8
proxitok-web     | [04-Aug-2023 01:17:18] NOTICE: ready to handle connections
proxitok-web     | 2023-08-04 01:17:19,201 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
proxitok-web     | 2023-08-04 01:17:19,201 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
proxitok-signer  | App listening on port: 8080
```
```
version: '3'

services:
  web:
    container_name: proxitok-web
    image: ghcr.io/pablouser1/proxitok:master
    #image: ghcr.io/pablouser1/proxitok@sha256:80ccad758027ff0367ee640935ec97fcb32f42fdab5a800032ec0a63690f1196
    ports:
      - 127.0.0.1:1122:80
    environment:
      - LATTE_CACHE=/cache
      - API_CACHE=redis
      - REDIS_HOST=proxitok-redis
      - REDIS_PORT=6379
      - API_SIGNER=remote
      - API_SIGNER_URL=http://proxitok-signer:8080/signature
    volumes:
      - proxitok-cache:/cache
    depends_on:
      - redis
      - signer
    networks:
      - proxitok
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

  redis:
    container_name: proxitok-redis
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    networks:
      - proxitok
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /data:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    cap_drop:
      - ALL

  signer:
    container_name: proxitok-signer
    image: ghcr.io/pablouser1/signtok:master
    init: true
    networks:
      - proxitok
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  proxitok-cache:

networks:
  proxitok:
```
