### ISSUE TITLE
docker-compose error:(SIGNATURE_CONNECTION_ERROR)

### ISSUE THREAD

**Issue by ZevaXu** [pablouser1/ProxiTok#53]
Hello, I deployed with docker-compose, the web application is success to access but when go in to a url like `https://example.com/@xxx`, got a err below:
```
There was an error processing your request!

HTTP Code: 500

API error code 20 (SIGNATURE_CONNECTION_ERROR)
```
and I try set the `API_FORCE_LEGACY=1`, it still now work.

this is my docker-compose.yml:
```
version: '3'

services:
  web:
    container_name: proxitok-web
    image: ghcr.io/pablouser1/proxitok:master
    ports:
      - 8083:80
    environment:
      - LATTE_CACHE=/cache
      - API_CACHE=redis
      - REDIS_HOST=proxitok-redis
      - REDIS_PORT=6379
      - API_SIGNER_URL=http://proxitok-signer:8080/signature
      - API_FORCE_LEGACY=1
    volumes:
      - proxitok-cache:/cache
    depends_on:
      - redis
      - signer
  redis:
    container_name: proxitok-redis
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
  signer:
    container_name: proxitok-signer
    image: ghcr.io/pablouser1/signtok:master
volumes:
  proxitok-cache:
```
